name: Telegram Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'  # Әр 12 сағат сайын іске қосу

jobs:
  run-bot:
    runs-on: ubuntu-lates
    
    steps:
      - name: Репозиторийді жүктеу
        uses: actions/checkout@v3
        
      - name: Python орнату
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Тәуелділіктерді орнату
        run: |
          pip install -r requirements.txt
          
      - name: Ботты іске қосу
        run: python telegram_bot.py
